### ISSUE TITLE
Is the Ardoises Server down ?

### ISSUE THREAD

**Issue by himito** [saucisson/ardoises#3]
Hi!,

I was wondering if the server https://ardoises.ovh is down.

Thank you,

Jaime

**Comment by saucisson** [comment]
Hi,
yes the server is down, and the domain name has expired, as i have not had any news from the CosyVerif committee for one year.
Are you the new research engineer at University Paris 13?

**Comment by himito** [comment]
Thanks for your really fast reply :)

Yep, I am the new one 💃

**Comment by saucisson** [comment]
Welcome!

**Comment by saucisson** [comment]
I have reopened the server at https://ardoises.ovh. Feel free to ask any question, if you have some.
The documentation should  be at https://saucisson.github.io/ardoises/, but it is far from complete.

**Comment by himito** [comment]
Thanks a lot ! 😄
